name: 'Changes Review'
on:
    pull_request:
        branches: ['main']
jobs:
    cancel-workflows:
        permissions:
          actions: write
        runs-on: ubuntu-latest
        steps:
         - name: Cancel Previous Runs
           uses: styfle/cancel-workflow-action@0.9.1
    cdk:
        permissions:
          contents: read # for actions/checkout to fetch code
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
          actions: read
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: cdk synth
              uses: youyo/aws-cdk-github-actions@v2
              id: synth
              with:
                cdk_subcommand: 'synth'
                actions_comment: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                AWS_DEFAULT_REGION: 'us-east-1'
            - name: cdk diff
              id: diff
              uses: youyo/aws-cdk-github-actions@v2
              with:
                cdk_subcommand: 'diff'
                actions_comment: true
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                GITHUB_TOKEN: ${{ github.token }}
                AWS_DEFAULT_REGION: 'us-east-1'