name: Checkov
on:
    workflow_dispatch:
    push:
        branches: ['main', 'develop']
jobs:
    cancel-workflows:
        permissions:
          actions: write
        runs-on: ubuntu-latest
        steps:
         - name: Cancel Previous Runs
           uses: styfle/cancel-workflow-action@0.9.1
    scan-code-checkov:
        permissions:
          contents: read # for actions/checkout to fetch code
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
          actions: read
          pull-requests: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
          
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
    
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
          - uses: actions/checkout@v3
          - name: cdk synth
            uses: youyo/aws-cdk-github-actions@v2
            id: synth
            with:
              cdk_subcommand: 'synth'
              actions_comment: false
            env:
              GITHUB_TOKEN: ${{ github.token}}
              AWS_DEFAULT_REGION: 'us-east-1'  
          - name: Checkov GitHub Action
            uses: bridgecrewio/checkov-action@v12
            with:
              # This will add both a CLI output to the console and create a results.sarif file
              output_format: cli,sarif
              output_file_path: console,results.sarif
              directory: cdk.out/     
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            if: success() || failure()
            with:
              sarif_file: results.sarif