name: KICS
on:
    workflow_dispatch:
    push:
        branches: ['main', 'develop']
    pull_request:
        branches: ['main']
jobs:
    cancel-workflows:
        permissions:
          actions: write
        runs-on: ubuntu-latest
        steps:
         - name: Cancel Previous Runs
           uses: styfle/cancel-workflow-action@0.9.1
    scan-code-kics:
        permissions:
          contents: read
          security-events: write
          actions: read
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: cdk synth
              uses: youyo/aws-cdk-github-actions@v2
              id: synth
              with:
                cdk_subcommand: 'synth'
                actions_comment: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                AWS_DEFAULT_REGION: 'us-east-1'
            - name: run kics Scan
              if: github.event_name != 'pull_request'
              uses: checkmarx/kics-github-action@v1.7.0
              with:
                path: 'cdk.out'
                output_path: myResults
                fail_on: high
                token: ${{ secrets.GITHUB_TOKEN }}
                enable_comments: false
                output_formats: 'json,sarif'
            - name: run kics Scan
              if: github.event_name == 'pull_request'
              uses: checkmarx/kics-github-action@v1.7.0
              with:
                path: 'cdk.out'
                output_path: myResults
                fail_on: high
                token: ${{ secrets.GITHUB_TOKEN }}
                enable_comments: true
                output_formats: 'json,sarif'
            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v2
              if: success() || failure() && github.event_name != 'pull_request'
              with:
                sarif_file: myResults/results.sarif           