name: 'Tests Pipeline'
on:
    workflow_dispatch:
    push:
        branches: ["develop"]
    pull_request:
        branches: ["main"]
jobs:
    unity-test:
        runs-on: ubuntu-latest
        outputs:
            unity-test-status: ${{ steps.unity-test.outcome }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            - run: npm ci
            - run: npm test
              id: unity-test
    